# Generated by Django 4.1.3 on 2022-11-27 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_alter_article_options_alter_article_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='media',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Fotoğraf Ekle'),
        ),
    ]
