# Generated by Django 4.1.3 on 2022-11-29 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0005_yorumlar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yorumlar',
            name='yorumcu_yorumu',
            field=models.CharField(max_length=400, verbose_name='Yorum'),
        ),
    ]
