# Generated by Django 4.1.3 on 2022-11-30 09:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0006_alter_yorumlar_yorumcu_yorumu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yorumlar',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='article.article', verbose_name='Makale'),
        ),
    ]
