# Generated by Django 4.1.3 on 2022-11-30 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0009_alter_comment_article'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-yorumcu_date']},
        ),
    ]
